"""add authentication tables

Revision ID: 7f98b0ba77c4
Revises: 7f05d2d40075
Create Date: 2026-08-15 16:35:53.171668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f98b0ba77c4'
down_revision: Union[str, Sequence[str], None] = '7f05d2d40075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OAuthIdentities',
    sa.Column('identity_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'github')", name='ck_oauthidentities_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_oauthidentities_provider_provider_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauthidentities_user_provider')
    )
    op.create_table('PasswordCredentials',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PasswordCredentials')
    op.drop_table('OAuthIdentities')
    # ### end Alembic commands ###
