import { Button } from "../components/Button";
import { DocumentTitle } from "../components/DocumentTitle";
import { PublicNav } from "../components/PublicNav";

const features = [
  ["Practice history", "Bring Codeforces and LeetCode activity into one private record."],
  ["Useful patterns", "See how your practice develops across contests, topics, and difficulty."],
  ["A focused next step", "Use the dashboard to notice gaps without turning practice into noise."],
];

export function HomePage() {
  return <div className="site-page"><DocumentTitle title="Competitive programming, understood" description="CPIP brings competitive-programming history into one focused analytics workspace." /><PublicNav /><main><section className="hero container"><div className="hero-copy"><p className="eyebrow">Competitive Programming Intelligence Platform</p><h1>Understand the practice behind your progress.</h1><p className="hero-summary">CPIP brings your competitive-programming history into one quiet workspace, so patterns in your practice are easier to see and act on.</p><div className="hero-actions"><Button to="/signup">Create your account</Button><Button to="/login" variant="secondary">Sign in</Button></div></div><div className="product-preview" aria-label="Illustrative CPIP dashboard preview"><div className="preview-heading"><span>Practice overview</span><small>Upcoming analytics</small></div><div className="preview-grid"><div className="preview-panel preview-primary"><p>Submission history</p><div className="preview-bars" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /></div><small>Connected when your data is ready</small></div><div className="preview-panel"><p>Topic patterns</p><div className="preview-lines" aria-hidden="true"><i /><i /><i /></div><small>Built from real practice data</small></div></div></div></section><section id="features" className="feature-section container" aria-labelledby="features-title"><div className="section-intro"><p className="eyebrow">Built for deliberate practice</p><h2 id="features-title">A dashboard that stays close to the work.</h2></div><div className="feature-grid">{features.map(([title, description], index) => <article key={title} className="feature-item"><span className="feature-index">0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section id="how-it-works" className="workflow-section" aria-labelledby="workflow-title"><div className="container workflow-layout"><div><p className="eyebrow">How it works</p><h2 id="workflow-title">From platform activity to a useful personal record.</h2></div><ol className="workflow-list"><li><strong>Connect your history</strong><span>CPIP gathers the competitive-programming activity you choose to sync.</span></li><li><strong>Prepare your data</strong><span>PostgreSQL and FastAPI provide the foundation for user-scoped analytics.</span></li><li><strong>Review your dashboard</strong><span>Future dashboard sections will surface real patterns, never invented data.</span></li></ol></div></section><section className="final-cta container"><div><p className="eyebrow">Ready when you are</p><h2>Keep your practice history in one place.</h2></div></section></main><footer className="site-footer container"><span>CPIP — Competitive Programming Intelligence Platform</span><span>Private practice analytics, built incrementally.</span></footer></div>;
}
